/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author mendo
 */
public class View_Mendoza_Ruiz extends javax.swing.JFrame {

    /**
     * Creates new form View_Mendoza_Ruiz
     */
    public View_Mendoza_Ruiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRegistrarVehiculo = new javax.swing.JPanel();
        txtClave = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        errClave = new javax.swing.JLabel();
        errMarca1 = new javax.swing.JLabel();
        errModelo = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelPiezas = new javax.swing.JPanel();
        checkLlantas = new javax.swing.JCheckBox();
        checkFaros = new javax.swing.JCheckBox();
        checkSuspension = new javax.swing.JCheckBox();
        checkVocinas = new javax.swing.JCheckBox();
        checkTurbo = new javax.swing.JCheckBox();
        errPiezas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        errDescripcion = new javax.swing.JLabel();
        btnAdaptar = new javax.swing.JButton();
        txtClaveSearch = new javax.swing.JTextField();
        btnBuscarClave = new javax.swing.JButton();
        errClaveSearch = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbVehiculos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistrarVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Vehiculo :"));
        panelRegistrarVehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtClave.setBorder(javax.swing.BorderFactory.createTitledBorder("Clave :"));
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        panelRegistrarVehiculo.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 200, -1));

        txtMarca.setBorder(javax.swing.BorderFactory.createTitledBorder("Marca :"));
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        panelRegistrarVehiculo.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, -1));

        txtModelo.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo :"));
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        panelRegistrarVehiculo.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, -1));

        errClave.setText("errClave");
        panelRegistrarVehiculo.add(errClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, -1));

        errMarca1.setText("errMarca");
        panelRegistrarVehiculo.add(errMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, -1));

        errModelo.setText("errModelo");
        panelRegistrarVehiculo.add(errModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));

        btnRegistrar.setText("Registrar Vehiculo");
        panelRegistrarVehiculo.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 190, 40));

        jPanel1.add(panelRegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 460, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Unidad 3 - Taller 2 - P.O.O.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 40));

        panelPiezas.setBorder(javax.swing.BorderFactory.createTitledBorder("Piezas a Adaptar :"));
        panelPiezas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkLlantas.setText("Llantas");
        panelPiezas.add(checkLlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        checkFaros.setText("Faros");
        panelPiezas.add(checkFaros, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        checkSuspension.setText("Suspensión");
        panelPiezas.add(checkSuspension, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        checkVocinas.setText("Vocinas");
        panelPiezas.add(checkVocinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        checkTurbo.setText("Turbo");
        panelPiezas.add(checkTurbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        errPiezas.setText("errPiezas");
        panelPiezas.add(errPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción :"));
        jScrollPane1.setViewportView(txtDescripcion);

        panelPiezas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 250, 60));

        errDescripcion.setText("errDescripcion");
        panelPiezas.add(errDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 250, -1));

        btnAdaptar.setText("Adaptar al Vehiculo");
        panelPiezas.add(btnAdaptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 250, -1));

        jPanel1.add(panelPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 290, 220));

        txtClaveSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Clave :"));
        txtClaveSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtClaveSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, -1));

        btnBuscarClave.setText("Buscar");
        jPanel1.add(btnBuscarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 190, 40));

        errClaveSearch.setText("errClaveSearch");
        jPanel1.add(errClaveSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 200, -1));

        tbVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbVehiculos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 760, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtClaveSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Mendoza_Ruiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Mendoza_Ruiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Mendoza_Ruiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Mendoza_Ruiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Mendoza_Ruiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdaptar;
    public javax.swing.JButton btnBuscarClave;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JCheckBox checkFaros;
    public javax.swing.JCheckBox checkLlantas;
    public javax.swing.JCheckBox checkSuspension;
    public javax.swing.JCheckBox checkTurbo;
    public javax.swing.JCheckBox checkVocinas;
    public javax.swing.JLabel errClave;
    public javax.swing.JLabel errClaveSearch;
    public javax.swing.JLabel errDescripcion;
    public javax.swing.JLabel errMarca1;
    public javax.swing.JLabel errModelo;
    public javax.swing.JLabel errPiezas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel panelPiezas;
    public javax.swing.JPanel panelRegistrarVehiculo;
    public javax.swing.JTable tbVehiculos;
    public javax.swing.JTextField txtClave;
    public javax.swing.JTextField txtClaveSearch;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JTextField txtMarca;
    public javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
